update=śro, 23 sie 2017, 17:10:57
last_client=kicad
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=/mnt/big/CernLib/KiCad/SchLib/Capacitors/Capacitors Networks THD
LibName2=/mnt/big/CernLib/KiCad/SchLib/Capacitors/Capacitors Networks SMD
LibName3=/mnt/big/CernLib/KiCad/SchLib/Capacitors/Capacitors THD
LibName4=/mnt/big/CernLib/KiCad/SchLib/Capacitors/Capacitors SMD
LibName5=/mnt/big/CernLib/KiCad/SchLib/Connectors/Miscellaneous
LibName6=/mnt/big/CernLib/KiCad/SchLib/Connectors/HARWIN
LibName7=/mnt/big/CernLib/KiCad/SchLib/Connectors/LEMO
LibName8=/mnt/big/CernLib/KiCad/SchLib/Connectors/WEIDMULLER
LibName9=/mnt/big/CernLib/KiCad/SchLib/Connectors/FCI
LibName10=/mnt/big/CernLib/KiCad/SchLib/Connectors/MOLEX
LibName11=/mnt/big/CernLib/KiCad/SchLib/Connectors/TYCO
LibName12=/mnt/big/CernLib/KiCad/SchLib/Connectors/ERNI
LibName13=/mnt/big/CernLib/KiCad/SchLib/Connectors/MENTOR
LibName14=/mnt/big/CernLib/KiCad/SchLib/Connectors/SAMTEC
LibName15=/mnt/big/CernLib/KiCad/SchLib/Connectors/STELVIO-KONTEK COMATEL
LibName16=/mnt/big/CernLib/KiCad/SchLib/Connectors/AMPHENOL
LibName17=/mnt/big/CernLib/KiCad/SchLib/Connectors/HARTING
LibName18=/mnt/big/CernLib/KiCad/SchLib/Connectors/3M
LibName19=/mnt/big/CernLib/KiCad/SchLib/Eletro-mechanical/Pads
LibName20=/mnt/big/CernLib/KiCad/SchLib/Eletro-mechanical/Switches
LibName21=/mnt/big/CernLib/KiCad/SchLib/Eletro-mechanical/Relays
LibName22=/mnt/big/CernLib/KiCad/SchLib/Eletro-mechanical/Heat-Sinks
LibName23=/mnt/big/CernLib/KiCad/SchLib/Eletro-mechanical/Fasteners & Fixings
LibName24=/mnt/big/CernLib/KiCad/SchLib/Eletro-mechanical/Batteries
LibName25=/mnt/big/CernLib/KiCad/SchLib/Eletro-mechanical/Fuses
LibName26=/mnt/big/CernLib/KiCad/SchLib/Eletro-mechanical/Metal Screening Box
LibName27=/mnt/big/CernLib/KiCad/SchLib/Eletro-mechanical/Sockets
LibName28=/mnt/big/CernLib/KiCad/SchLib/ICs And Semiconductors/Regulators
LibName29=/mnt/big/CernLib/KiCad/SchLib/ICs And Semiconductors/Transistors
LibName30=/mnt/big/CernLib/KiCad/SchLib/ICs And Semiconductors/Power Supplies
LibName31=/mnt/big/CernLib/KiCad/SchLib/ICs And Semiconductors/Analog & Interface
LibName32=/mnt/big/CernLib/KiCad/SchLib/ICs And Semiconductors/Sensors
LibName33=/mnt/big/CernLib/KiCad/SchLib/ICs And Semiconductors/Logic
LibName34=/mnt/big/CernLib/KiCad/SchLib/ICs And Semiconductors/Optocouplers
LibName35=/mnt/big/CernLib/KiCad/SchLib/ICs And Semiconductors/Standard Logic
LibName36=/mnt/big/CernLib/KiCad/SchLib/ICs And Semiconductors/DC-DC Converters
LibName37=/mnt/big/CernLib/KiCad/SchLib/ICs And Semiconductors/Operational Amplifiers
LibName38=/mnt/big/CernLib/KiCad/SchLib/ICs And Semiconductors/Crystals & Oscillators
LibName39=/mnt/big/CernLib/KiCad/SchLib/ICs And Semiconductors/Diodes
LibName40=/mnt/big/CernLib/KiCad/SchLib/ICs And Semiconductors/LEDs & Displays
LibName41=/mnt/big/CernLib/KiCad/SchLib/ICs And Semiconductors/PCB Modules
LibName42=/mnt/big/CernLib/KiCad/SchLib/ICs And Semiconductors/Bonding
LibName43=/mnt/big/CernLib/KiCad/SchLib/Resistors/Resistors THD
LibName44=/mnt/big/CernLib/KiCad/SchLib/Resistors/Potentiometers SMD
LibName45=/mnt/big/CernLib/KiCad/SchLib/Resistors/Thermistors And Varistors
LibName46=/mnt/big/CernLib/KiCad/SchLib/Resistors/Potentiometers THD
LibName47=/mnt/big/CernLib/KiCad/SchLib/Resistors/Resistor Networks THD
LibName48=/mnt/big/CernLib/KiCad/SchLib/Resistors/Resistors SMD
LibName49=/mnt/big/CernLib/KiCad/SchLib/Resistors/Resistor Networks SMD
LibName50=/mnt/big/CernLib/KiCad/SchLib/Inductors & Transformers/Transformers
LibName51=/mnt/big/CernLib/KiCad/SchLib/Inductors & Transformers/Inductors SMD
LibName52=/mnt/big/CernLib/KiCad/SchLib/Inductors & Transformers/Inductors THD
LibName53=/mnt/big/CernLib/KiCad/SchLib/Inductors & Transformers/Cores
LibName54=/home/twl/Kicad-dev/kicad-library/library/power
LibName55=/home/twl/Kicad-dev/kicad-library/library/conn
LibName56=dsi_shield
